-- ============================================================
-- MathU Racing Game — Database Schema
-- Target: MySQL 8.0+   Character Set: utf8mb4
-- Run manually: mysql -u root -p < schema.sql
-- ============================================================

CREATE DATABASE IF NOT EXISTS mathu_racegame
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE mathu_racegame;

-- ============================================================
-- BOUNDED CONTEXT 1: Core Domain — User & Race State
-- ============================================================

CREATE TABLE users (
    id            BIGINT       NOT NULL AUTO_INCREMENT,
    username      VARCHAR(50)  NOT NULL,
    email         VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          ENUM('TEACHER','STUDENT') NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
                               ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT pk_users          PRIMARY KEY (id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email    UNIQUE (email)
) ENGINE = InnoDB;

CREATE TABLE races (
    id          BIGINT       NOT NULL AUTO_INCREMENT,
    title       VARCHAR(100) NOT NULL,
    -- 6-char alphanumeric, auto-generated by service layer (no O/0/I/1 chars)
    entry_code  CHAR(6)      NOT NULL,
    status      ENUM('LOBBY','ACTIVE','FINISHED') NOT NULL DEFAULT 'LOBBY',
    created_by  BIGINT       NOT NULL,
    winner_id   BIGINT       NULL,           -- NULL until a participant reaches position 1000
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at  TIMESTAMP    NULL,
    finished_at TIMESTAMP    NULL,

    CONSTRAINT pk_races            PRIMARY KEY (id),
    CONSTRAINT uq_races_entry_code UNIQUE (entry_code),
    CONSTRAINT fk_races_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_races_winner_id  FOREIGN KEY (winner_id)  REFERENCES users (id)
) ENGINE = InnoDB;

-- High-frequency write target: current_position updated on every correct answer.
-- Composite index supports the primary SSE broadcast query:
--   SELECT * FROM race_participants WHERE race_id = ? ORDER BY current_position DESC
CREATE TABLE race_participants (
    id               BIGINT    NOT NULL AUTO_INCREMENT,
    race_id          BIGINT    NOT NULL,
    user_id          BIGINT    NOT NULL,
    current_position INT       NOT NULL DEFAULT 0,  -- range: 0–1000
    version          BIGINT    NOT NULL DEFAULT 0,  -- JPA @Version optimistic locking
    joined_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_race_participants PRIMARY KEY (id),
    CONSTRAINT uq_rp_race_user      UNIQUE (race_id, user_id),
    CONSTRAINT fk_rp_race           FOREIGN KEY (race_id) REFERENCES races (id),
    CONSTRAINT fk_rp_user           FOREIGN KEY (user_id) REFERENCES users (id),

    -- Leaderboard query: covering index on race_id + ordered position
    INDEX idx_rp_race_position (race_id, current_position DESC)
) ENGINE = InnoDB;

-- ============================================================
-- BOUNDED CONTEXT 2: Question Domain — Procedural Generation
-- RULE: No foreign keys into the Core Domain. Zero coupling.
-- ============================================================

-- Template examples:
--   "{NAME} {ACTION} {AMOUNT} {OBJECT}."
--   "{NUMBER} {OPERATOR} {NUMBER} = ?"
CREATE TABLE question_templates (
    id               BIGINT       NOT NULL AUTO_INCREMENT,
    template_text    VARCHAR(500) NOT NULL,
    subject_area     VARCHAR(50)  NOT NULL,  -- e.g. 'ARITHMETIC', 'WORD_PROBLEM'
    difficulty_level TINYINT      NOT NULL DEFAULT 1,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_question_templates PRIMARY KEY (id),
    CONSTRAINT chk_qt_difficulty     CHECK (difficulty_level BETWEEN 1 AND 5),

    -- Generation lookup: filter by subject + difficulty before random selection
    INDEX idx_qt_subject_difficulty (subject_area, difficulty_level)
) ENGINE = InnoDB;

-- Unified variable dictionary for all placeholder types (Option A — single table).
-- Adding a new variable type requires only a new ENUM value and rows — no schema change.
CREATE TABLE template_variables (
    id            BIGINT       NOT NULL AUTO_INCREMENT,
    variable_type ENUM('NAME','ACTION','OBJECT','NUMBER','OPERATOR','AMOUNT') NOT NULL,
    value         VARCHAR(100) NOT NULL,
    -- Optional structured metadata. Examples:
    --   NUMBER:   {"range": [1, 100]}
    --   OPERATOR: {"symbol": "+", "operation": "addition"}
    metadata      JSON         NULL,

    CONSTRAINT pk_template_variables PRIMARY KEY (id),

    -- Primary generation lookup: SELECT ... WHERE variable_type = ? ORDER BY RAND() LIMIT 1
    INDEX idx_tv_variable_type (variable_type)
) ENGINE = InnoDB;
