package com.mathu.racegame.race.entity;

import com.mathu.racegame.user.entity.User;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "races")
@Getter
@Setter
@NoArgsConstructor
public class Race {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, length = 100)
    private String title;

    // Immutable after creation — generated by EntryCodeGenerator
    @Column(name = "entry_code", nullable = false, unique = true, length = 6, updatable = false)
    private String entryCode;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 10)
    private RaceStatus status;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", nullable = false)
    private User createdBy;

    // Null until a participant reaches position 1000 — FK enforced by DB schema
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "winner_id")
    private User winner;

    // LAZY: never eager-load participants from Race; query via RaceParticipantRepository directly
    @OneToMany(mappedBy = "race", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    private List<RaceParticipant> participants = new ArrayList<>();

    // Set by teacher at race creation. Controls question difficulty per mode:
    // Normal = base, Highway = base+1 (capped at 5), Dirt Road = base-1 (floored at 1)
    @Column(name = "base_difficulty", nullable = false)
    private int baseDifficulty = 2;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "started_at")
    private LocalDateTime startedAt;

    @Column(name = "finished_at")
    private LocalDateTime finishedAt;

    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.status = RaceStatus.LOBBY;
    }
}
